title: Sibil Hadzhitodorov's IT Portfolio
description: A collection of my cybersecurity, system administration, and cloud computing projects.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
plugins:
  - jekyll-seo-tag
