title: Sibil Hadzhitodorov's IT Portfolio
description: A collection of my system administration, cybersecurity, and cloud computing projects.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
plugins:
  - jekyll-seo-tag
